### ISSUE TITLE
如何让每周夜聊更有效率？

### ISSUE THREAD

**Issue by tcfh2016** [LakesideCommunity/ReadingClub#3]
参加了两次夜聊，第一次感觉颇好，第二次效率较低。相比之下第一次新鲜，并且有输出，第二次更为发散。所以，是不是可以为每次夜聊设定几个基本的框架，比如：

- 闲聊10分钟。
- 最分享的事，每人5分钟，估时45分钟。
- 事务状态10分钟。

夜聊的主题可以定位“新鲜”，让大伙儿了解下彼此的生活状态，有没有困难，有没有难忘的事，有没有好的点子，有没有可以分享的书籍、材料等，而事务状态简单同步下，详细的可以通过github上讨论与跟踪。

**Comment by tcfh2016** [comment]
@sunwenbo 空的时候上来讨论下，刚在写下周计划，偶然想到的。

**Comment by sunwenbo** [comment]
上一次的夜聊效率相对高一些了，根据上一次夜聊的情况，我建议夜聊分两部分：第一部分，谈正事；第二部分，每个人轮流分享值得分享和推荐的东西。目前可以不用定细的规定，等多开几次夜聊会议后就能摸索出更多经验了，如有必要，再增加细的规定。

**Comment by tcfh2016** [comment]
是的，上一次的感受不错的，同意。这个issue讨论到此，先关闭。之后如果有需要，再reopen。
