### ISSUE TITLE
波兰朋友分享筹备讨论

### ISSUE THREAD

**Issue by sunwenbo** [LakesideCommunity/ReadingClub#6]
怎样保证这次分享的效果，并借此机会形成我们的流程。

**Comment by tcfh2016** [comment]
保证效果有两个条件有关：

- 多人参与。
- 观点交流。

第一点需要大家平日里足够活跃，不是一时半会可以准备好的事。对于后面一点，这次分享有明确的主题吗？感兴趣的同学可以准备相关的问题，并在分享过程中或者之后进行讨论。

**Comment by nebula912** [comment]
从增加参与者的参与程度做起吧，如果只是匆匆过客一般的参与没什么价值，最好多些成果性的东西。

**Comment by foreversunshine** [comment]
那是不是要在现场做一些笔录什么，或者每个人写个作业？

**Comment by tcfh2016** [comment]
@LakesideCommunity/river 这个问题已经开得比较久了，这周在群里面讨论得比较多，本来我是想将讨论搬移上来，后来想想，那个时候大伙儿说话都比较快，怕太感性，于是就先不放在这里了。

对于 @foreversunshine 提到的这个问题，也不用每个人，不过一次分享总得有个人做点笔记的好，每次可提前商量看谁愿意，那么这次分享就由他做次记录或者小结，如果过后其他小伙伴有意愿也写点想法可以综合一下一次发出，总结言简意赅就好，可以适当添加自己的真情实感，让写作的人也觉得有收获，也不用花太多时间。

**Comment by tcfh2016** [comment]
主题过期关闭。
